name: orc8r-accessd

on:
  push:
    paths:
      - 'orchestrator-bundle/orc8r-accessd-operator/**'

jobs:
  orc8r-accessd-lint-report:
    name: Lint report (orc8r-accessd)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: cd orchestrator-bundle/orc8r-accessd-operator && tox -e lint

  orc8r-accessd-static-analysis:
    name: Static analysis (orc8r-accessd)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: cd orchestrator-bundle/orc8r-accessd-operator && tox -e static

  orc8r-accessd-unit-tests-with-coverage:
    name: Unit tests (orc8r-accessd)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: cd orchestrator-bundle/orc8r-accessd-operator && tox -e unit

#  orc8r-accessd-integration-test:
#    name: Integration tests (orc8r-accessd)
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Setup operator environment
#        uses: charmed-kubernetes/actions-operator@main
#        with:
#          provider: microk8s
#      - name: Run integration tests
#        run: cd orchestrator-bundle/orc8r-accessd-operator && tox -e integration
