name: Upload orc8r-bundle

on:
  push:
    branches:
      - "main"
    paths:
      - "orchestrator-bundle/orc8r-bundle/**"

jobs:
  orc8r-bundle-charmhub-upload:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
      - name: install jinja2
        run: pip install -U Jinja2
      - name: render bundle.yaml
        run: |
          python orchestrator-bundle/orc8r-bundle/render_bundle.py \
          --template orchestrator-bundle/orc8r-bundle/bundle.yaml.j2 --output orchestrator-bundle/orc8r-bundle/bundle.yaml --channel edge
      - name: copy README.md
        run: |
          cp README.md orchestrator-bundle/orc8r-bundle/
      - name: Upload bundle
        uses: canonical/charming-actions/upload-bundle@1.0.2
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          bundle-path: ./orchestrator-bundle/orc8r-bundle
          github-token: "${{ secrets.GITHUB_TOKEN }}"
