name: Upload orc8r-bundle

on:
  push:
    branches:
      - "main"
    paths:
      - "orchestrator-bundle/orc8r-bundle"

jobs:
  orc8r-bundle-charmhub-upload:
    runs-on: ubuntu-latest
    name: Charmhub upload orc8r-bundle
    steps:
      - uses: actions/checkout@v2

      - name: Upload bundle
        uses: canonical/charming-actions/upload-bundle@1.0.2
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          bundle-path: ./orchestrator-bundle/orc8r-bundle
          github-token: "${{ secrets.GITHUB_TOKEN }}"
