name: CI

on:
  push:
    paths:
      - 'orchestrator-bundle/nms-magmalte-operator/**'

jobs:
  nms-magmalte-lint-report:
    name: Lint report (nms-magmalte)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: cd orchestrator-bundle/nms-magmalte-operator && tox -e lint

  nms-magmalte-static-analysis:
    name: Static analysis (nms-magmalte)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: cd orchestrator-bundle/nms-magmalte-operator && tox -e static

  nms-magmalte-unit-tests-with-coverage:
    name: Unit tests (nms-magmalte)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: cd orchestrator-bundle/nms-magmalte-operator && tox -e unit

#  nms-magmalte-integration-test:
#    name: Integration tests (nms-magmalte)
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Setup operator environment
#        uses: charmed-kubernetes/actions-operator@main
#        with:
#          provider: microk8s
#      - name: Run integration tests
#        run: cd orchestrator-bundle/nms-magmalte-operator && tox -e integration
