name: orc8r-directoryd

on:
  push:
    paths:
      - "orchestrator-bundle/orc8r-directoryd-operator/**"

jobs:
  orc8r-directoryd-lint-report:
    uses: ./.github/workflows/lint-report.yml
    with:
      charm_dir: orc8r-directoryd-operator

  orc8r-directoryd-static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      charm_dir: orc8r-directoryd-operator

  orc8r-directoryd-unit-tests-with-coverage:
    uses: ./.github/workflows/unit-tests.yml
    with:
      charm_dir: orc8r-directoryd-operator

  orc8r-directoryd-integration-test:
    uses: ./.github/workflows/integration-tests.yml
    with:
      charm_dir: orc8r-directoryd-operator

  orc8r-directoryd-charmhub-upload:
    if: github.ref_name == 'main'
    uses: ./.github/workflows/upload-charm.yml
    secrets: inherit
    with:
      charm: orc8r-directoryd-operator
