name: orc8r-streamer

on:
  push:
    paths:
      - "orchestrator-bundle/orc8r-streamer-operator/**"

jobs:
  orc8r-streamer-lint-report:
    uses: ./.github/workflows/lint-report.yml
    with:
      charm_dir: orc8r-streamer-operator

  orc8r-streamer-static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      charm_dir: orc8r-streamer-operator

  orc8r-streamer-unit-tests-with-coverage:
    uses: ./.github/workflows/unit-tests.yml
    with:
      charm_dir: orc8r-streamer-operator

  orc8r-streamer-integration-test:
    uses: ./.github/workflows/integration-tests.yml
    with:
      charm_dir: orc8r-streamer-operator

  orc8r-streamer-charmhub-upload:
    if: github.ref_name == 'main'
    uses: ./.github/workflows/upload-charm.yml
    secrets: inherit
    with:
      charm: orc8r-streamer-operator
